version: "3.9"
services:
  server:
    build: .
    environment:
      - REDIS_HOST=redis
    ports:
      - "9120:9120/udp"
  web:
    build: ./web/
    environment:
      - "REDIS_URL=redis://redis:6379"
    ports:
      - "80:80"
  redis:
    image: "redis:latest"